---
- hosts: all

  roles:
  - jm1.base_system
  - jm1.container_docker
  - jm1.dev_cpp
  - jm1.dev_hpc
  - role: jm1.distcc
    vars:
      distcc_start: "true"
      distcc_allowed_nets:
      - "0.0.0.0/0"
      distcc_listener: []

# NOTE: Roles must resemble the development environment you use for consistent distcc builds,
#       e.g. compilers, headers and libraries on server and client side should match.

  post_tasks:
  - # Clean up the apt cache reduces the image size, since the apt cache is not stored in a layer.
    # Ref.: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
    shell: rm -rf /var/lib/apt/lists/*
    args:
      # Silence warning "Consider using the file module with state=absent rather
      # than running rm. If you need to use command because file is insufficient
      # you can add warn=False to this command task or set command_warnings=False
      # in ansible.cfg to get rid of this message." because Ansible's file module
      # does not feature a state=empty yet.
      # Ref.: https://github.com/ansible/ansible/issues/18910
      warn: false
