---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- copy:
    src: "{{ distribution_id|join('-') }}/"
    dest: /
    mode: preserve

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- jm1.pkg.meta_pkg:
    name: "jm1-docker-artifacts-hpc"
    version: "3"
    depends:
    - libblas-dev
    - libboost-dev
    - libeigen3-dev
    - liblapack-dev
    - liblapacke-dev
    - libopencv-dev
    - libnetcdf-c++4-dev
    - libnetcdf-dev
    - netcdf-bin
    - paraview
    - paraview-dev # e.g. for compiling and linking simulation software against ParaView Catalyst
    - python3-numpy
    - python3-paraview
    - python3-pytest
    - libpython3.9-dev # workaround for bug 972551, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972551
    - hdf5-tools

    # NOTE:
    # - libnetcdf-c++4-dev and libnetcdf-dev are for handling netCDF files as used for Grids in DLRs TAU
    # - paraview packages are for reading/writing and visualizing *.vtk files as produced by tau2vtk
    # - python3-vtk9 and dependent VTK packages like libvtk9-dev and vtk9-examples, have been removed because they break
    #   python3-paraview. Use VTK headers and libraries from paraview-dev instead.
    # - python3-pytest, libeigen3-dev and libboost-dev are required for pybind11 tests only

- shell: "/usr/local/bin/make_install_{{ item|lower }}.sh"
  register: install_result
  changed_when:
    not (install_result.rc == 124 and install_result.stderr == (item + " is already installed. Skipping.."))
  failed_when: not (
        (install_result.rc == 0) or
        (install_result.rc == 124 and install_result.stderr == (item + " is already installed. Skipping.."))
    )
  loop:
  - FLAME
  - Elemental
  - fmt
  - pybind11

- set_fact:
    install_result: !!null
