---
- hosts: all

  pre_tasks:
  - user:
      name: devil
      password: ""
      groups:
      - audio
      - video
      system: no
      uid: 1000
      shell: "/bin/bash"

  roles:
  - jm1.base_system
  - jm1.container_docker
  - jm1.dev_cpp
  - jm1.dev_hpc
  - jm1.kdevelop

  post_tasks:
  - file:
      path: /usr/local/src/kdesrc/build/
      state: absent
