---
- src: jm1.base_system
- src: jm1.container_docker
- src: jm1.container_systemd
- src: jm1.dev_cpp
- src: jm1.dev_freetz
- src: jm1.dev_hpc
- src: jm1.dev_haskell
- src: jm1.dev_openwrt
- src: jm1.dev_prolog
- src: jm1.kdevelop
- src: jm1.sudo
- src: jm1.virtual_pkg
