---
- hosts: all

  pre_tasks:
  - user:
      name: devil
      password: ""
      groups:
      - audio
      - video
      system: no
      uid: 1000
      shell: "/bin/bash"

  roles:
  - jm1.base_system
  - jm1.container_docker
  - jm1.container_systemd
