---
roles:
- src: jm1.common
- src: jm1.base_system
- src: jm1.container_docker
- src: jm1.dev_cpp # e.g. required by jm1.kdevelop
- src: jm1.dev_hpc
- src: jm1.kdevelop

collections:
- jm1.pkg # e.g. required by jm1.base_system
