---
- hosts: all

  pre_tasks:
  - user:
      name: devil
      password: ""
      groups:
      - video
      system: no
      uid: 1000
      shell: "/bin/bash"

  roles:
  - jm1.base_system
  - jm1.container_docker
  - jm1.container_systemd
  - jm1.dev_cpp
  - jm1.dev_embedded
  - jm1.dev_freetz
  - jm1.dev_haskell
  - jm1.dev_hpc
  - jm1.dev_java
  - jm1.dev_openwrt
  - jm1.dev_prolog
  - jm1.dev_python
  - role: jm1.kdevelop
    vars:
      install_from_source: no

  post_tasks:
  - # Clean up the apt cache reduces the image size, since the apt cache is not stored in a layer.
    # Ref.: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
    shell: rm -rf /var/lib/apt/lists/*
    args:
      # Silence warning "Consider using the file module with state=absent rather
      # than running rm. If you need to use command because file is insufficient
      # you can add warn=False to this command task or set command_warnings=False
      # in ansible.cfg to get rid of this message." because Ansible's file module
      # does not feature a state=empty yet.
      # Ref.: https://github.com/ansible/ansible/issues/18910
      warn: false
  - file:
      path: /usr/local/src/kdesrc/build/
      state: absent
