---
roles:
- src: jm1.common
- src: jm1.base_system
- src: jm1.container_docker
- src: jm1.container_systemd
- src: jm1.dev_cpp # e.g. required by jm1.kdevelop
- src: jm1.dev_embedded
- src: jm1.dev_freetz
- src: jm1.dev_haskell
- src: jm1.dev_hpc
- src: jm1.dev_java
- src: jm1.dev_openwrt
- src: jm1.dev_prolog
- src: jm1.dev_python
- src: jm1.kdevelop
- src: jm1.systemd # e.g. required by jm1.container_systemd

collections:
- jm1.pkg # e.g. required by jm1.base_system
