---
roles:
- src: jm1.common
- src: jm1.container_systemd
- src: jm1.dev_cpp
- src: jm1.dev_embedded
- src: jm1.dev_freetz
- src: jm1.dev_haskell
- src: jm1.dev_hpc
- src: jm1.dev_java
- src: jm1.dev_openwrt
- src: jm1.dev_prolog
- src: jm1.dev_python
- src: jm1.kdevelop

collections:
- jm1.cloudy
- jm1.pkg
