---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- jm1.pkg.meta_pkg:
    name: "jm1-docker-artifacts-python"
    version: "1"
    depends:
    - cython
    - cython3
    - ipython3
    - flake8
    - pipenv
    - pycodestyle # formerly called pep8
    - pypy
    - pypy-doc
    - pyqt5-dev
    - pyqt5-dev-tools
    - pyqt5-examples
    - python-pip
    - python3-pip
    - python-pytest
    - python3-pytest
    - swig
    - virtualenv
    suggests:
    - pipx
    - python3-pyside2.qt3danimation
    - python3-pyside2.qt3dcore
    - python3-pyside2.qt3dextras
    - python3-pyside2.qt3dinput
    - python3-pyside2.qt3dlogic
    - python3-pyside2.qt3drender
    - python3-pyside2.qtcharts
    - python3-pyside2.qtconcurrent
    - python3-pyside2.qtcore
    - python3-pyside2.qtdatavisualization
    - python3-pyside2.qtgui
    - python3-pyside2.qthelp
    - python3-pyside2.qtlocation
    - python3-pyside2.qtmultimedia
    - python3-pyside2.qtmultimediawidgets
    - python3-pyside2.qtnetwork
    - python3-pyside2.qtopengl
    - python3-pyside2.qtopenglfunctions
    - python3-pyside2.qtpositioning
    - python3-pyside2.qtprintsupport
    - python3-pyside2.qtqml
    - python3-pyside2.qtquick
    - python3-pyside2.qtquickcontrols2
    - python3-pyside2.qtquickwidgets
    - python3-pyside2.qtremoteobjects
    - python3-pyside2.qtscript
    - python3-pyside2.qtscripttools
    - python3-pyside2.qtscxml
    - python3-pyside2.qtsensors
    - python3-pyside2.qtserialport
    - python3-pyside2.qtsql
    - python3-pyside2.qtsvg
    - python3-pyside2.qttest
    - python3-pyside2.qttexttospeech
    - python3-pyside2.qtuitools
    - python3-pyside2.qtwebchannel
    - python3-pyside2.qtwebengine
    - python3-pyside2.qtwebenginecore
    - python3-pyside2.qtwebenginewidgets
    - python3-pyside2.qtwebsockets
    - python3-pyside2.qtwidgets
    - python3-pyside2.qtx11extras
    - python3-pyside2.qtxml
    - python3-pyside2.qtxmlpatterns
    - python-pyqt5.qtmultimedia
    - python-pyqt5.qtopengl
    - python-pyqt5.qtpositioning
    - python-pyqt5.qtquick
    - python-pyqt5.qtsensors
    - python-pyqt5.qtserialport
    - python-pyqt5.qtsql
    - python-pyqt5.qtsvg
    - python-pyqt5.qtwebchannel
    - python-pyqt5.qtwebengine
    - python-pyqt5.qtwebkit
    - python-pyqt5.qtwebsockets
    - python-pyqt5.qtx11extras
    - python-pyqt5.qtxmlpatterns
    - python3-dbus.mainloop.pyqt5
    - python3-pyqt5
    - python3-pyqt5.qtmultimedia
    - python3-pyqt5.qtopengl
    - python3-pyqt5.qtpositioning
    - python3-pyqt5.qtquick
    - python3-pyqt5.qtsensors
    - python3-pyqt5.qtserialport
    - python3-pyqt5.qtsql
    - python3-pyqt5.qtsvg
    - python3-pyqt5.qtwebchannel
    - python3-pyqt5.qtwebengine
    - python3-pyqt5.qtwebkit
    - python3-pyqt5.qtwebsockets
    - python3-pyqt5.qtx11extras
    - python3-pyqt5.qtxmlpatterns
