---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

apt_keys: |
  {{
    {
      'Debian_9': [
        apt_keys_debian.stretch_stable,
        apt_keys_debian.stretch_security_automatic,
        apt_keys_debian.stretch_automatic
      ],
      'Debian_10': [
        apt_keys_debian.buster_stable,
        apt_keys_debian.buster_security_automatic,
        apt_keys_debian.buster_automatic
      ],
      'Debian_11': [
        apt_keys_debian.buster_stable,
        apt_keys_debian.buster_security_automatic,
        apt_keys_debian.buster_automatic
      ],
      'Ubuntu_18_04': [
        apt_keys_ubuntu.ubuntu_2012_archive,
        apt_keys_ubuntu.ubuntu_2012_cdimage
      ],
      'Ubuntu_20_04': [
        apt_keys_ubuntu.ubuntu_2012_archive,
        apt_keys_ubuntu.ubuntu_2012_cdimage,
        apt_keys_ubuntu.ubuntu_2018_archive
      ]
    }[distribution_id|join('_')|regex_replace('[^A-Za-z0-9 _-]', '_')]
  }}

# apt_keys_debian is set in role jm1.pkg.apt_keys
# apt_keys_ubuntu is set in role jm1.pkg.apt_keys

apt_repositories: |
  {{
    {
      'Debian_9': [
        apt_repositories_debian_9.stretch.deb,
        apt_repositories_debian_9.stretch_security.deb,
        apt_repositories_debian_9.stretch_updates.deb
      ],
      'Debian_10': [
        apt_repositories_debian_10.buster.deb,
        apt_repositories_debian_10.buster_security.deb,
        apt_repositories_debian_10.buster_updates.deb
      ],
      'Debian_11': [
        apt_repositories_debian_11.bullseye.deb,
        apt_repositories_debian_11.bullseye_security.deb,
        apt_repositories_debian_11.bullseye_updates.deb
      ],
      'Ubuntu_18_04': [
        apt_repositories_ubuntu_18_04.bionic.deb,
        apt_repositories_ubuntu_18_04.bionic_partner.deb,
        apt_repositories_ubuntu_18_04.bionic_security.deb,
        apt_repositories_ubuntu_18_04.bionic_updates.deb
      ],
      'Ubuntu_20_04': [
        apt_repositories_ubuntu_20_04.focal.deb,
        apt_repositories_ubuntu_20_04.focal_partner.deb,
        apt_repositories_ubuntu_20_04.focal_security.deb,
        apt_repositories_ubuntu_20_04.focal_updates.deb
      ]
    }[distribution_id|join('_')|regex_replace('[^A-Za-z0-9 _-]', '_')]
  }}

# apt_repositories_debian_9 is set in role jm1.pkg.apt_repositories
# apt_repositories_debian_10 is set in role jm1.pkg.apt_repositories
# apt_repositories_debian_11 is set in role jm1.pkg.apt_repositories
# apt_repositories_ubuntu_18_04 is set in role jm1.pkg.apt_repositories
# apt_repositories_ubuntu_20_04 is set in role jm1.pkg.apt_repositories

ansible_python_interpreter: |-
  {{ '/usr/bin/python' if distribution_id is defined and distribution_id == ['CentOS', '7'] else '/usr/bin/python3' }}
